### ISSUE TITLE
Add an end-point just to delete the DB file for a service

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-service#105]
Refrance
https://github.com/NubeIO/rubix-service/blob/master/src/system/resources/app/delete_data.py

We really need a way just to delete the data base for each service
JSON
- wires
- wires-plat

SQL
- lora-raw
- point-server
- bacnet-server

**Comment by RaiBnod** [comment]
Add `config` and `data` directory inside `out` and need to delete `out/data` only with above API.
