### ISSUE TITLE
Add enable/disable for services

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-service#118]
![image](https://user-images.githubusercontent.com/18637436/111045090-69d2f980-84a0-11eb-9f1b-4d8b12c241f0.png)

**Comment by RaiBnod** [comment]
Add `is_enabled` on `src/system/resources/fields.py > service_field` for making user to know whether it's currently `enabled` or `disabled`. We will be showing `ENABLED` button on if it's `DISABLED` and vice-versa on frontend.

**Comment by RaiBnod** [comment]
Subtask in wires-plat: https://app.clickup.com/3370523/v/b/li/7658656
