### ISSUE TITLE
please remove RUBIX_GPIO as an app

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-service#274]

**Comment by RaiBnod** [comment]
Now, we have more device types as well. We can merge those `apps.json` & `apps.master.json` into one. And add a field on `installable_apps[i].applicable_devices = [type1, type2]`.

So, for device `type3`, the above app won't be available & for device `type1`, `type2` the above app will be available.

Available device types are:

- rubix-compute (if we have device_type blank treat it as rubix-compute, to make appropriate app listing we need to change device-type)
- rubix-compute-io
- edge-28
- cloud
- edge-gateway


And also, put that validation of device-type on the backend now.
