### ISSUE TITLE
Time Settings

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/rubix-service#275]
Some devices don't have RTCs AND don't have network access to sync time so a user needs to be able to the time easily from the platform.  
We need to be able to change all time settings through the platform:
- manually set date and time
- set timezone (done)

and advanced settings: (maybe hidden from initially in collapsible UI section)
- set the NTP server
- enable/disable NTP sync

**Comment by RaiBnod** [comment]
Some of the useful commands:

https://www.linuxuprising.com/2019/07/how-to-set-timezone-and-enable-network.html


- timedatectl
- timedatectl list-timezones
- timedatectl set-timezone \<timezone\>
- timedatectl set-ntp true
- sudo systemctl restart systemd-timedated
---------------

- timedatectl show-timesync
- vim /etc/systemd/timesyncd.conf
   - FallbackNTP=[0.debian.pool.ntp.org](http://0.debian.pool.ntp.org/) 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
   or
   - FallbackNTP=ntp.ubuntu.com
- sudo systemctl restart systemd-timesyncd

**Comment by NubeDev** [comment]
dont do this task yet
closed untill other task are finishefd

**Comment by RaiBnod** [comment]
NTP servers list: https://gist.github.com/mutin-sa/eea1c396b1e610a2da1e5550d94b0453
