### ISSUE TITLE
Let user download the zip build

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-service#73]
Let user download the build
![image](https://user-images.githubusercontent.com/18637436/105781481-cb113d00-5fc6-11eb-8050-0967dff657b8.png)

See example
![image](https://user-images.githubusercontent.com/18637436/105781381-9dc48f00-5fc6-11eb-93f1-8738b1bb6f5e.png)

**Comment by RaiBnod** [comment]
Make an additional field `browser_download_url` available for `GET: /api/app` and `GET: /api/app/stats/<string:app_service>`.

Check this API: https://api.github.com/repos/NubeIO/rubix-service/releases/tags/v1.3.1 for the field.
