### ISSUE TITLE
Bacnet master/server issues are starting/stop same service

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-service#74]
Bacnet master/server issues are starting/stop same service
Not sure if its frontend or backend issue

![bacnet-server-master](https://user-images.githubusercontent.com/18637436/105781718-188daa00-5fc7-11eb-98b1-4e5cdd94a9a8.gif)

**Comment by RaiBnod** [comment]
We already solved that on pull request #72. Now creating a new release for this.
